loadstring(
    game:HttpGet(
        'https://raw.githubusercontent.com/Lirum86/Steal-a-Brainrod/refs/heads/main/Neig.lua'
    )
)()
loadstring(
    game:HttpGet(
        'https://raw.githubusercontent.com/Lirum86/Steal-a-Brainrod/refs/heads/main/GG.lua'
    )
)()
